import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generatePDF = async (videoDetails) => {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const drawBorder = () => {
    doc.setDrawColor(100);
    doc.rect(10, 10, pageWidth - 20, pageHeight - 20);
  };

  const drawHeader = (title) => {
    doc.setFillColor(41, 128, 185); 
    doc.rect(10, 10, pageWidth - 20, 20, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(255, 255, 255);
    doc.text(title, pageWidth / 2, 23, { align: "center" });

    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
  };

  const drawFooter = () => {
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by Vistora", pageWidth / 2, pageHeight - 12, {
      align: "center",
    });
  };

  drawBorder();
  drawHeader("Video Analysis Report");
  let currentY = 40;

  autoTable(doc, {
    startY: currentY,
    theme: "grid",
    styles: { halign: "left", cellPadding: 4 },
    headStyles: {
      fillColor: [52, 152, 219],
      textColor: 255,
      fontStyle: "bold",
    },
    head: [["Field", "Value"]],
    body: [
      ["Video Name", videoDetails.originalName || "Untitled"],
      ["Status", videoDetails.isAnalyzed ? "Analyzed" : "Pending"],
      ["Uploaded", new Date(videoDetails.createdAt).toLocaleString()],
    ],
  });
  currentY = doc.lastAutoTable.finalY + 10;

  if (videoDetails.summaryPoints) {
    doc.setFontSize(14);
    doc.setTextColor(33, 33, 33);
    currentY += 5;

    autoTable(doc, {
      startY: currentY,
      theme: "grid",
      styles: { fontSize: 12, cellPadding: 8 },
      head: [["Summary"]],
      body: [[videoDetails.summaryPoints]],
    });
  }

  drawFooter();

  if (videoDetails.keywords?.length > 0) {
    doc.addPage();
    drawBorder();
    drawHeader("Keywords");
    currentY = 40;

    autoTable(doc, {
      startY: currentY,
      theme: "grid",
      styles: { fontStyle: "italic", cellPadding: 3 },
      head: [["Keyword"]],
      body: videoDetails.keywords.map((kw) => [kw]),
    });

    drawFooter();
  }

  if (videoDetails.segments?.length > 0) {
    doc.addPage();
    drawBorder();
    drawHeader("Segments");
    currentY = 40;

    autoTable(doc, {
      startY: currentY,
      theme: "grid",
      styles: {cellPadding: 3 },
      head: [["Segment Title"]],
      body: videoDetails.segments.map((s) => [s.title || s]),
    });

    drawFooter();
  }

  doc.save(`${videoDetails.originalName || "video-report"}.pdf`);
};
